name: dbt run

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-athena-community awscli

      - name: Test AWS connection
        run: |
          aws sts get-caller-identity
          aws s3 ls s3://weather-pipeline-merida/athena-results/
          aws athena list-work-groups --region us-east-2

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << 'EOF'
          weather_pipeline:
            target: dev
            outputs:
              dev:
                type: athena
                work_group: primary
                region_name: us-east-2
                s3_staging_dir: s3://weather-pipeline-merida/athena-results/
                s3_data_dir: s3://weather-pipeline-merida/silver/
                schema: weather_pipeline
                database: awsdatacatalog
                work_group: primary
                threads: 1
          EOF

      - name: Run dbt
        working-directory: weather_pipeline
        run: dbt run